/**
 * SLATemplate class representing an SLA template.
 *
 * Properties:
 * - id: string - Unique identifier (autogenerated upon creation by route/service)
 * - filepath: string - Path to the SLA template file
 */

class SLATemplate {
  /**
   * Create an SLA Template
   * @param {Object} opts
   * @param {string} opts.id - unique id for the SLA template
   * @param {string} opts.filepath - template file path
   */
  constructor(opts = {}) {
    if (!opts || typeof opts !== 'object') {
      throw new TypeError('SLATemplate constructor expects an options object');
    }

    const { id, filepath } = opts;

    if (typeof id !== 'string' || id.length === 0) {
      throw new TypeError('SLATemplate.id must be a non-empty string');
    }
    if (typeof filepath !== 'string' || filepath.length === 0) {
      throw new TypeError('SLATemplate.filepath must be a non-empty string');
    }

    this.id = id;
    this.filepath = filepath;
  }

  /** Serialize for storage */
  toJSON() {
    return {
      id: this.id,
      filepath: this.filepath
    };
  }

  /** Hydrate from storage */
  static fromJSON(obj) {
    return new SLATemplate({
      id: obj.id,
      filepath: obj.filepath
    });
  }
}

module.exports = SLATemplate;
